SET SERVEROUTPUT ON
DECLARE
    TYPE empleado IS RECORD
    (nombre VARCHAR2(100),
    salario EMPLOYEES.SALARY%TYPE,
    cod_dept EMPLOYEES.DEPARTMENT_ID%TYPE);
    
    TYPE empleados is table of
        empleado
    INDEX BY PLS_INTEGER;
    
    emple1 empleadoS;

BEGIN
    FOR I IN 100..206 LOOP
    SELECT first_name||' '||last_name, salary, department_id INTO EMPLE1(I) FROM EMPLOYEES WHERE EMPLOYEE_ID=I;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('VISUALIZANDO TODA LA COLECCION ');
    FOR I IN emple1.FIRST..emple1.LAST LOOP
     DBMS_OUTPUT.PUT_LINE(emple1(I).nombre||' '||emple1(I).salario||' '||emple1(I).cod_dept);
     END LOOP;
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO EL PRIMER EMPLEADO');
     DBMS_OUTPUT.PUT_LINE(emple1(emple1.FIRST).nombre);
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO EL ULTIMO EMPLEADO');
     DBMS_OUTPUT.PUT_LINE(emple1(emple1.LAST).nombre);
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO EL NUMERO DE EMPLEADOS');
     DBMS_OUTPUT.PUT_LINE(emple1.COUNT);
     DBMS_OUTPUT.PUT_LINE('BORRANDO EMPLEADOS QUE GANEN MENOS DE 7000');
     FOR I IN emple1.FIRST..emple1.LAST LOOP
     IF emple1(I).salario < 7000 THEN
     emple1.DELETE(I) ;
     END IF;
     END LOOP;
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO DESPUES DE BORRAR EMPLEADOS QUE GANABAN MENOS DE 7000');
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO EL PRIMER EMPLEADO');
     DBMS_OUTPUT.PUT_LINE(emple1(emple1.FIRST).nombre);
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO EL ULTIMO EMPLEADO');
     DBMS_OUTPUT.PUT_LINE(emple1(emple1.LAST).nombre);
     DBMS_OUTPUT.PUT_LINE('VISUALIZANDO EL NUMERO DE EMPLEADOS DESPUES');
     DBMS_OUTPUT.PUT_LINE(emple1.COUNT);
END;