--Ejercicio 2
CREATE OR REPLACE PROCEDURE VISUALIZAR
IS
    CURSOR CURSOR_EMPL IS SELECT FIRST_NAME, SALARY FROM EMPLOYEES;
    NOMBRE_EMPL EMPLOYEES.FIRST_NAME%TYPE;
    SALARIO EMPLOYEES.SALARY%TYPE;
BEGIN
    FOR I IN CURSOR_EMPL LOOP
    DBMS_OUTPUT.PUT_LINE(I.FIRST_NAME||' '||I.SALARY);
    END LOOP;
END;
/

EXECUTE VISUALIZAR;
/

--Ejercicio 2
CREATE OR REPLACE PROCEDURE VISUALIZAR
(EMPL IN EMPLOYEES.DEPARTMENT_ID%TYPE, cantidad_empl OUT NUMBER)
IS
    CURSOR CURSOR_EMPL IS SELECT FIRST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES WHERE DEPARTMENT_ID=EMPL;
    NOMBRE_EMPL EMPLOYEES.FIRST_NAME%TYPE;
    SALARIO EMPLOYEES.SALARY%TYPE;
BEGIN
    CANTIDAD_EMPL:=0;
    FOR I IN CURSOR_EMPL LOOP
    DBMS_OUTPUT.PUT_LINE(I.DEPARTMENT_ID||' '||I.FIRST_NAME||' '||I.SALARY);
    CANTIDAD_EMPL:=CANTIDAD_EMPL+1;
    END LOOP;
END;
/

SET SERVEROUTPUT ON
DECLARE
  PARAMETRO_DEP NUMBER;
  CANTIDAD NUMBER;
begin
  PARAMETRO_DEP:=50;
  VISUALIZAR(PARAMETRO_DEP,CANTIDAD);
  DBMS_OUTPUT.PUT_LINE('CANTIDAD DE EMPLEADOS: '||CANTIDAD);
end;

--Ejercicio 3
CREATE OR REPLACE PROCEDURE NUMEROFORMATEADO (NUM_FORMATEAR IN OUT
VARCHAR2)
IS
    BLOQUE1 VARCHAR2(20);
    BLOQUE2 VARCHAR2(20);
    BLOQUE3 VARCHAR2(20);
    BLOQUE4 VARCHAR2(20);
BEGIN
    BLOQUE1:=substr(NUM_FORMATEAR,1,4);
    BLOQUE2:=substr(NUM_FORMATEAR,5,4);
    BLOQUE3:=substr(NUM_FORMATEAR,9,2);
    BLOQUE4:=substr(NUM_FORMATEAR,10);
NUM_FORMATEAR:=BLOQUE1 || '-' || BLOQUE2 || '-' || BLOQUE3 || '-' || BLOQUE4;
END;
/

SET SERVEROUTPUT ON
DECLARE
  NUM_FORMATEAR VARCHAR(30);
begin
  NUM_FORMATEAR:='11111111111111111111';
  DBMS_OUTPUT.PUT_LINE('FORMATO ORIGINAL: '||NUM_FORMATEAR);
  NUMEROFORMATEADO(NUM_FORMATEAR);
  DBMS_OUTPUT.PUT_LINE('NUEVO FORMATO: '||NUM_FORMATEAR);
end;