SET SERVEROUTPUT ON
DECLARE
    NAME VARCHAR(100);
    LASTNAME VARCHAR(100);
BEGIN
    NAME:='OSCAR ALEJANDRO';
    LASTNAME:='LOPEZ CLIMACO';
    DBMS_OUTPUT.PUT_LINE(NAME);
    DBMS_OUTPUT.PUT_LINE(LASTNAME);
    DBMS_OUTPUT.PUT_LINE(NAME||' '||LASTNAME);
END;