CREATE OR REPLACE PACKAGE NOMINA IS
    FUNCTION CALCULAR_NOMINA(ID_N NUMBER) RETURN NUMBER;
    FUNCTION CALCULAR_NOMINA(ID_N NUMBER,PORCENTAJE VARCHAR) RETURN NUMBER;
    FUNCTION CALCULAR_NOMINA(ID_N NUMBER,PORCENTAJE NUMBER, TERCERO
    VARCHAR2:='V') RETURN NUMBER;
END NOMINA;

CREATE OR REPLACE PACKAGE BODY NOMINA IS
    FUNCTION CALCULAR_NOMINA ( ID_N NUMBER ) RETURN NUMBER IS
    SALARIO_FINAL NUMBER;
    SALARIO NUMBER;
    BEGIN
    SELECT SALARY INTO SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID=ID_N;
    SALARIO_FINAL := SALARIO - ( SALARIO * 0.15 );
    RETURN SALARIO_FINAL;
    END;
    
    FUNCTION CALCULAR_NOMINA ( ID_N NUMBER,PORCENTAJE VARCHAR )
    RETURN NUMBER IS
    SALARIO_FINAL NUMBER;
    SALARIO NUMBER;
    BEGIN
    SELECT SALARY INTO SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID=ID_N;
    SALARIO_FINAL := SALARIO - ( SALARIO * (TO_NUMBER(PORCENTAJE)/100 ));
    RETURN SALARIO_FINAL;
    END;
    
    FUNCTION CALCULAR_NOMINA (ID_N NUMBER,PORCENTAJE NUMBER,TERCERO VARCHAR2 := 'V') RETURN NUMBER IS
    SALARIO_FINAL NUMBER;
    COMISION NUMBER;
    SALARIO NUMBER;
    BEGIN
    SELECT SALARY INTO SALARIO FROM EMPLOYEES WHERE EMPLOYEE_ID=ID_N;
    SELECT COMMISSION_PCT INTO COMISION FROM EMPLOYEES WHERE
    EMPLOYEE_ID=ID_N;
    SALARIO_FINAL := SALARIO - ( SALARIO * (PORCENTAJE/100 )) + (SALARIO*COMISION);
    RETURN SALARIO_FINAL;
    END;
END NOMINA;
    /
SET SERVEROUTPUT ON
DECLARE
    X NUMBER;
    BEGIN
    X:=NOMINA.CALCULAR_NOMINA(150,'8');
    DBMS_OUTPUT.PUT_LINE(X);
END;
/
DESC NOMINA;