--ejercicio1
SET SERVEROUTPUT ON
DECLARE
    X NUMBER:=10; 
BEGIN 
    DBMS_OUTPUT.PUT_LINE(X); 
    DECLARE 
        X NUMBER:=20; 
    BEGIN 
        DBMS_OUTPUT.PUT_LINE(X); 
    END; 
    DBMS_OUTPUT.PUT_LINE(X); 
END;

--ejercicio 2
SET SERVEROUTPUT ON
DECLARE
    X NUMBER:=20;
BEGIN
    DBMS_OUTPUT.PUT_LINE(X);
    BEGIN
        DBMS_OUTPUT.PUT_LINE(X);
    END;
    DBMS_OUTPUT.PUT_LINE(X);
END;

--ejercicio 3
SET SERVEROUTPUT ON
DECLARE
X NUMBER:=10;
BEGIN
DBMS_OUTPUT.PUT_LINE(X);
BEGIN
DBMS_OUTPUT.PUT_LINE(X);
END;
DBMS_OUTPUT.PUT_LINE(X);
END;
